# Generated by Django 5.0.6 on 2024-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodyct_name', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=1, max_digits=20)),
            ],
        ),
    ]
